/**
 * The Mint Compass — Mint & Co's symbol (single source of truth).
 *
 * Four tapered mint-leaf blades (N/S long, E/W shorter), each split along its
 * own spine into two lateral halves — one near-flat deep green, the other a
 * gradient rising to a pale mint tip — for a faceted, dimensional look. A
 * small sharp centre spark sits in the negative space where the blade bases
 * meet, framed by a broken deep-green ring.
 *
 * Hand-traced vector, matched against the approved reference artwork
 * (public/brand/mint-compass-mark-source.png, an AI-generated 1024x1024
 * study). Colours below were sampled directly from that file with `sharp`:
 *   deep #164B39 · mid #3A785A · pastel mint tip #89CDA4
 * Recreated as SVG (not shipped as that PNG) because raster art can't stay
 * crisp across the full size range this mark needs — 16px favicon through a
 * browser-zoomed navbar. viewBox 0 0 128 128.
 *
 * Everything consumes this module: the lockup (header/footer), the app icon,
 * the OG card, and the /public reference assets.
 */

import { Wordmark } from "./Wordmark";

export type CompassVariant = "colour" | "mono" | "light" | "dark";

const DEEP = "#164B39";
const DEEP_SHADE = "#123F30";
const MID = "#3A785A";
const PASTEL = "#89CDA4";
const RING = "#164B39";
const SPARK = "#164B39";

// Blade halves, split along the blade's own spine (the straight edge is an
// implicit close — "Z" draws it). N points up (long, tip y=6, base y=59); E
// points right (shorter, tip x=114, base x=69). S/W are generated by
// mirroring N/E, which keeps the light/deep half assignment consistent
// (mirror symmetry about each axis pair) rather than free-hand redrawing.
const N_LIGHT = // right half — gradient (base -> tip)
  "M64 6 C73 15.5 77 27 76 39 C75.3 48.5 70.5 55.5 64 59 Z";
const N_DEEP = // left half — near-flat
  "M64 6 C55 15.5 51 27 52 39 C52.7 48.5 57.5 55.5 64 59 Z";
const E_LIGHT = // top half — gradient (base -> tip)
  "M114 64 C104.5 57 93 53.5 81 54.5 C72 55.3 66.5 59.5 69 64 Z";
const E_DEEP = // bottom half — near-flat
  "M114 64 C104.5 71 93 74.5 81 73.5 C72 72.7 66.5 68.5 69 64 Z";
// Gradient vectors, in the blade's own base->tip direction (userSpaceOnUse —
// this rides through the S/W mirror transforms automatically, no duplicate
// gradients needed).
const N_VEC = 'x1="64" y1="59" x2="64" y2="6"';
const E_VEC = 'x1="69" y1="64" x2="114" y2="64"';

// Concave four-point spark, radius r, centred at (64,64).
function sparkStar(r: number): string {
  const c = +(r * 0.24).toFixed(2);
  const t = (n: number) => +n.toFixed(2);
  return (
    `M64 ${t(64 - r)} Q${t(64 + c)} ${t(64 - c)} ${t(64 + r)} 64 ` +
    `Q${t(64 + c)} ${t(64 + c)} 64 ${t(64 + r)} ` +
    `Q${t(64 - c)} ${t(64 + c)} ${t(64 - r)} 64 ` +
    `Q${t(64 - c)} ${t(64 - c)} 64 ${t(64 - r)} Z`
  );
}
const SPARK_PATH = sparkStar(5.2);

/** Four ring arcs with gaps at the cardinals (blade tips pierce through). */
function ringArcs(r: number, gapDeg: number): string {
  const pt = (deg: number) => {
    const rad = (deg * Math.PI) / 180;
    return `${(64 + r * Math.cos(rad)).toFixed(2)} ${(64 - r * Math.sin(rad)).toFixed(2)}`;
  };
  const seg = (from: number, to: number) => `M${pt(from)} A${r} ${r} 0 0 1 ${pt(to)}`;
  return [
    seg(90 - gapDeg, 0 + gapDeg),
    seg(0 - gapDeg, -90 + gapDeg),
    seg(-90 - gapDeg, -180 + gapDeg),
    seg(180 - gapDeg, 90 + gapDeg),
  ].join(" ");
}
const RING_PATH = ringArcs(51, 13);

type Spec = {
  deepFillN: string;
  lightFillN: string;
  deepFillE: string;
  lightFillE: string;
  ring: string;
  ringWidth: number;
  spark: string;
  defs: string;
};

function spec(variant: CompassVariant, simplified: boolean, id: string): Spec {
  const ringWidth = simplified ? 4.8 : 4.2;
  if (variant === "light") {
    return {
      deepFillN: "#3F8A68",
      lightFillN: "#BFE8D2",
      deepFillE: "#3F8A68",
      lightFillE: "#BFE8D2",
      ring: "#79C7A4",
      ringWidth,
      spark: "#F2FBF7",
      defs: "",
    };
  }
  if (variant === "mono") {
    return {
      deepFillN: "#176B4F",
      lightFillN: "#176B4F",
      deepFillE: "#176B4F",
      lightFillE: "#176B4F",
      ring: "#176B4F",
      ringWidth,
      spark: "#176B4F",
      defs: "",
    };
  }
  if (variant === "dark" || simplified) {
    return { deepFillN: DEEP, lightFillN: MID, deepFillE: DEEP, lightFillE: MID, ring: RING, ringWidth, spark: SPARK, defs: "" };
  }
  // colour, detailed — the traced gradient, oriented along each blade's own
  // base->tip axis (not a diagonal bbox gradient).
  return {
    deepFillN: `url(#${id}nd)`,
    lightFillN: `url(#${id}nl)`,
    deepFillE: `url(#${id}ed)`,
    lightFillE: `url(#${id}el)`,
    ring: RING,
    ringWidth,
    spark: SPARK,
    defs:
      `<defs>` +
      `<linearGradient id="${id}nd" gradientUnits="userSpaceOnUse" ${N_VEC}><stop offset="0" stop-color="${DEEP_SHADE}"/><stop offset="1" stop-color="${DEEP}"/></linearGradient>` +
      `<linearGradient id="${id}nl" gradientUnits="userSpaceOnUse" ${N_VEC}><stop offset="0" stop-color="${DEEP}"/><stop offset="0.55" stop-color="${MID}"/><stop offset="1" stop-color="${PASTEL}"/></linearGradient>` +
      `<linearGradient id="${id}ed" gradientUnits="userSpaceOnUse" ${E_VEC}><stop offset="0" stop-color="${DEEP_SHADE}"/><stop offset="1" stop-color="${DEEP}"/></linearGradient>` +
      `<linearGradient id="${id}el" gradientUnits="userSpaceOnUse" ${E_VEC}><stop offset="0" stop-color="${DEEP}"/><stop offset="0.55" stop-color="${MID}"/><stop offset="1" stop-color="${PASTEL}"/></linearGradient>` +
      `</defs>`,
  };
}

/** Build the compass SVG markup. */
export function compassSvg(
  variant: CompassVariant = "colour",
  { simplified = false }: { simplified?: boolean } = {},
): string {
  const id = `mc-${variant}${simplified ? "s" : ""}-`;
  const s = spec(variant, simplified, id);
  const ring = `<path d="${RING_PATH}" stroke="${s.ring}" stroke-width="${s.ringWidth}" stroke-linecap="round" fill="none"/>`;
  const half = (d: string, fill: string) => `<path d="${d}" fill="${fill}"/>`;
  const nPair = half(N_LIGHT, s.lightFillN) + half(N_DEEP, s.deepFillN);
  const ePair = half(E_LIGHT, s.lightFillE) + half(E_DEEP, s.deepFillE);
  const blades =
    nPair +
    `<g transform="matrix(1 0 0 -1 0 128)">${nPair}</g>` +
    ePair +
    `<g transform="matrix(-1 0 0 1 128 0)">${ePair}</g>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" fill="none">${s.defs}${ring}${blades}<path d="${SPARK_PATH}" fill="${s.spark}"/></svg>`;
}

/** Colour mark as a data URI, for next/og ImageResponse (<img src>). */
export const compassDataUri = `data:image/svg+xml,${encodeURIComponent(compassSvg("colour"))}`;

/**
 * The Mint Compass symbol, inline. Decorative (aria-hidden) — it always ships
 * beside the "Mint & Co" wordmark, which carries the accessible name.
 */
export function CompassMark({
  size = 32,
  className = "",
  variant = "colour",
  simplified = false,
}: {
  size?: number;
  className?: string;
  variant?: CompassVariant;
  simplified?: boolean;
}) {
  return (
    <span
      aria-hidden="true"
      className={`inline-block shrink-0 [&>svg]:block [&>svg]:h-full [&>svg]:w-full ${className}`}
      style={{ width: size, height: size, lineHeight: 0 }}
      dangerouslySetInnerHTML={{ __html: compassSvg(variant, { simplified }) }}
    />
  );
}

/**
 * The primary lockup: Mint Compass beside the "Mint & Co" wordmark, optically
 * centred as one brand unit. Used in the header and footer. Gap is tuned
 * tight — the new mark's viewBox has no wasted padding (unlike the old PNG),
 * so a small CSS gap now reads correctly instead of doubling up with it.
 */
export function LogoLockup({
  className = "",
  markSize = 34,
}: {
  className?: string;
  markSize?: number;
}) {
  const wordSize = markSize >= 40 ? "lg" : markSize >= 30 ? "md" : "sm";
  return (
    <span className={`inline-flex items-center gap-2 ${className}`}>
      <CompassMark size={markSize} />
      <Wordmark size={wordSize} />
    </span>
  );
}
